 -----------------------------------PACKAGE SPECIFICATION--------------------------
CREATE OR REPLACE PACKAGE SCHOOL_API IS
PROCEDURE GET_NAME_ADDRESS(SNAME NUMBER,STID NUMBER);
FUNCTION INSTRUCTOR_STATUS(IID NUMBER) RETURN NUMBER;
END SCHOOL_API;

---------------------------------PACKAGE BODY---------------------------------------
SET SERVEROUTPUT ON;
CREATE OR REPLACE PACKAGE BODY SCHOOL_API IS

PROCEDURE GET_NAME_ADDRESS(SNAME NUMBER,STID NUMBER) IS
FNAME1 VARCHAR2(20);
LNAME1 VARCHAR2(20);
BEGIN
SELECT FNAME,LNAME
INTO FNAME1,LNAME1
FROM STUDENT1
WHERE RNO=STID;
DBMS_OUTPUT.PUT_LINE('FIRST NAME='||FNAME1);
DBMS_OUTPUT.PUT_LINE('LAST NAME='||LNAME1);
END GET_NAME_ADDRESS;

FUNCTION INSTRUCTOR_STATUS(IID NUMBER) RETURN NUMBER IS
COUNT1 NUMBER;
BEGIN
SELECT COUNT(SECTION)
INTO COUNT1
FROM CLASS
WHERE FID=IID
GROUP BY FID;
RETURN COUNT1;
END;

END SCHOOL_API;

------------------------------------PL/SQL STATEMENT----------------------------------

SET SERVEROUTPUT ON;
DECLARE
STID NUMBER:=&N1;
SNAME NUMBER:=5;
TID NUMBER:=&N3;
COUNT2 NUMBER;
BEGIN
SCHOOL_API.GET_NAME_ADDRESS(SNAME,STID);
COUNT2:=SCHOOL_API.INSTRUCTOR_STATUS(TID);
DBMS_OUTPUT.PUT_LINE('TOTAL NJ. OF SECTIONS='||COUNT2);
IF COUNT2<=3 THEN DBMS_OUTPUT.PUT_LINE('NO NEED OF VACATION FOR THE FACULTY');
ELSE DBMS_OUTPUT.PUT_LINE('VACATION SHOULD BE GIVEN FOR THE FACULTY');
END IF;
END;
