---------------------------PACKAGE SPECIFICATION----------------------------
CREATE OR REPLACE PACKAGE SCHOOL_API IS 
PROCEDURE REMOVE_STUDENT(ST_ID NUMBER,OPT NUMBER);
END SCHOOL_API;

-------------------------------PACKAGE BODY----------------------------------


CREATE OR REPLACE PACKAGE BODY SCHOOL_API IS

PROCEDURE REMOVE_STUDENT(ST_ID NUMBER,OPT NUMBER) IS
MY_EXCEPT EXCEPTION;
COUNT1 NUMBER:=0;
BEGIN
SELECT COUNT(*)
INTO COUNT1
FROM ENROLLMENT
WHERE RNO=ST_ID;

IF(COUNT1=0)
THEN
DELETE
FROM STUDENT1
WHERE RNO=ST_ID;
DBMS_OUTPUT.PUT_LINE('ENTERED STUDENT IS NOT ENROLLED AND IS DELETED DIRECTLY');
ELSE
DBMS_OUTPUT.PUT_LINE('SOME ENROLLMENTS EXITS WITH THAT ROLL NUMBER');
     IF(OPT=1) THEN
     DBMS_OUTPUT.PUT_LINE('NO TUPLE HAS BEEN DELETED');
     ELSE
     DELETE
     FROM ENROLLMENT
     WHERE RNO=ST_ID;
     DELETE
     FROM STUDENT1
     WHERE RNO=ST_ID;
     DBMS_OUTPUT.PUT_LINE('TUPLES ARE DELETED BASED ON CASCADE');
    END IF;
END IF;
END;

END SCHOOL_API;


--------------------PL/SQL STATEMENTS----------------------------------

SET SERVEROUTPUT ON;
ACCEPT N1 PROMPT 'ENTER THE STUDENT ROLL NUMBER TO BE DELETED'
ACCEPT N2 PROMPT 'ENTER 1 FOR DELETE_RESTRICT ELSE ENTER 0 FOR DELETE_CASCADE'
DECLARE
STID NUMBER:=&N1;
OPT NUMBER:=&N2;
BEGIN
SCHOOL_API.REMOVE_STUDENT(STID,OPT);
END;
